package com.vasco.mydigipass.sdk.oauth.enums;

public enum ErrorType {
    UNKNOWN_ERROR_KEY,
    NOT_AUTHENTICATED,
    ACCOUNT_DISABLED,
    INVALID_REQUEST,
    NO_PERMISSIONS,
    ACCESS_DENIED,
    AUTHENTICATION_METHOD_NOT_ALLOWED,
    EID_SCOPE_NOT_ALLOWED
}
